name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.7

      - name: Autenticação no Docker
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Contrução da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            dowglasmaia/admin-skill-api:latest
            dowglasmaia/admin-skill-api:${{github.run_number}}
          
        
      - name: Publicando a imagem no Docker Hub
        run: echo "Docker push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com Kubernetes
        run: echo "Configuração do kubconfig"
      - name: Executar o deploy
        run: echo "kubectl aplly"
